{
 "title": "Redis master monitor",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Redis availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "redis_up" }
   ]
  },
  {
   "title": "Redis intrinsic latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Latency (microseconds)" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_duration_seconds_total{cmd=\"latency\"}[30s]) * 1000000.0",
     "legendFormat": "Intrinsic Latency"
    }
   ]
  },
  {
   "title": "Redis memory stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "KB" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes * 0.001",
     "legendFormat": "Total used KB"
    },
    {
     "expr": "redis_mem_fragmentation_bytes * 0.001\n",
     "legendFormat": "Total memory fragmentation KB"
    }
   ]
  },
  {
   "title": "Redis command rate ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Avg commands per second" }
   ],
   "targets": [
    {
     "expr": "irate(redis_commands_processed_total[30s])",
     "legendFormat": "Client command rate"
    }
   ]
  },
  {
   "title": "Avg command processing time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Time (microseconds)" }
   ],
   "targets": [
    {
     "expr": "irate(redis_commands_duration_seconds_total{cmd=\"client\"}[30s]) * 1000000",
     "legendFormat": "Time spent in processing client requests"
    }
   ]
  }
 ]
}