global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    monitor: "prometheus-stack-monitor"

rule_files:
  - '/etc/prometheus/prometheus.rules.yml'

scrape_configs:
  - job_name: prometheus
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'redis_monitor'
    
    scrape_interval: 5s

    static_configs:
      - targets: ['redis-app_redis_exporter_1:9121']
        labels:
          group: 'redis'
